import { harnessRuleLimits, harnessRuleSummaries } from '../rules/catalog';

export function agentRules(projectType: string): string {
	return `# AGENTS.md\n\nThis is a Harness ${projectType}. Treat Harness as the operating contract for every code change in this project.\n\n## Required Harness Workflow\n\n- Read this file and the \`.codex/skills/harness/SKILL.md\` skill before changing code.\n- Use Harness generators for supported code shapes instead of hand-rolling new structure.\n- Ask \`harness info <topic>\` before adding unfamiliar code or choosing a scaffold shape.\n- Add or update a feature spec before implementation.\n- Keep files small, focused, and aligned with the Harness rule catalog.\n- Run \`bun run check\` before handing work back; it includes formatting, type checks, lint, tests, build, and \`bun run audit\`.\n\n## Code Rules\n\n${harnessRuleSummaries.map((rule) => `- ${rule}`).join('\n')}\n\nHard limits: files ${harnessRuleLimits.maxFileLines}, functions ${harnessRuleLimits.maxFunctionLines}, classes ${harnessRuleLimits.maxClassLines}, methods ${harnessRuleLimits.maxMethodLines}, nesting ${harnessRuleLimits.maxNestingDepth}.\n`;
}

export function skillRules(projectType: string): string {
	return `# Harness Project Discipline\n\nUse this skill whenever you are planning, implementing, reviewing, or verifying code in this Harness ${projectType}.\n\n## Operating Rules\n\n1. Treat \`harness info\`, Harness generators, and \`harness audit\` as mandatory project controls.\n2. Run \`harness info <topic>\` or \`harness info scaffolds --json\` before creating unfamiliar code shapes.\n3. Prefer \`harness generate <kind> <name>\` for supported scaffolds, then adapt the generated file within Harness limits.\n4. Add or update the feature spec first so the intended behavior is explicit before implementation.\n5. Keep generated and hand-edited files inside the Harness rule catalog limits.\n6. Verify with \`bun run check\` before handing work back.\n\n## Hard Limits\n\n- Files: ${harnessRuleLimits.maxFileLines} lines.\n- Functions: ${harnessRuleLimits.maxFunctionLines} lines.\n- Classes: ${harnessRuleLimits.maxClassLines} lines.\n- Methods: ${harnessRuleLimits.maxMethodLines} lines.\n- Nesting: ${harnessRuleLimits.maxNestingDepth} levels.\n- Parameters: ${harnessRuleLimits.maxParameters}.\n- Classes per file: ${harnessRuleLimits.maxClassesPerFile}.\n`;
}
